config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  match 'api', to: 'pastes#api', via: [:post]
  resources :comments
  resources :pastes 
  devise_for :users, controllers: { registrations: 'registrations' }
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: "pastes#index"
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :paste

  validates :user_id, :paste_id, presence: true
  validates :body, presence: true, length: { in: 3..512 }

  def user_email
    self.user.email
  end
end

app/models/paste.rb
class Paste < ActiveRecord::Base
  belongs_to :user

  has_many :comments

  enum language: [:plaintext, :python, :ruby, :haml, :perl, :php, :scala, :groovy,
    :go, :gradle, :html, :lasso, :css, :scss, :less, :stylus, :markdown, :asciidoc,
    :django, :twig]

  scope :unexpired, -> { where('expires_at IS NULL OR expires_at > ?', Time.now) }
  scope :expired, -> { where.not.unexpired }

  validates :language, inclusion: { in: Paste.languages.keys }
  validates :user_id, presence: true
  validates :name, length: { maximum: 128 }
  validates :body, presence: true, length: { in: 3..512 }
  validate :expires_at_is_in_the_future,
    unless: "expires_at.nil?"

  def user_email
    self.user.email
  end

  private

  def expires_at_is_in_the_future
    if expires_at < Date.today
      errors.add(:expires_at, "Expire date must be in the future.")
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  include Gravtastic
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  gravtastic

  has_many :comments
  has_many :pastes

  before_create { |u| u.api_key = SecureRandom.hex }

  validates :api_key, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < InheritedResources::Base
  before_filter :authenticate_user!
  
  def create
    @comment = current_user.comments.build(comment_params)

    if @comment.save
      redirect_to paste_path(@comment.paste), flash: { success: 'Comment was successfully added.' }
    else
      redirect_to root_path, flash: { success: 'Unable to add comment.' }
    end
  end

  private

  def comment_params
    params.require(:comment).permit([:body, :paste_id])
  end
end

app/controllers/pastes_controller.rb
class PastesController < InheritedResources::Base
  before_action :set_pastes
  before_action :set_paste, only: [:show, :edit, :update, :destroy]

  before_filter :authenticate_user!, except: :api

  protect_from_forgery except: :api

  def show
    @comment = current_user.comments.build
  end

  def new
    @paste = current_user.pastes.build
  end

  def api
    begin
      @user = User.find_by! api_key: params[:api_key]
    rescue ActiveRecord::RecordNotFound
      head :bad_request
    end

    ApiRequestJob.perform_later(@user.id, params[:file].read)

    head 200
  end

  def create
    @paste = current_user.pastes.build(paste_params)

    if @paste.save
      redirect_to new_paste_path, flash: { success: 'Paste was successfully created.' }
    else
      render 'new'
    end
  end

  def update
    if @paste.update(paste_params)
      redirect_to paste_path(@paste), flash: { success: 'Paste was successfully updated.' }
    else
      redirect_to paste_path(@paste), flash: { warning: 'Unable to update paste.' }
    end
  end

  private

  def paste_params
    params.require(:paste).permit([:name, :body, :expires_at, :language])
  end

  def set_pastes
    @pastes = Paste.order(:created_at).unexpired.page params[:page]
  end

  def set_paste
    begin
      @paste = Paste.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      redirect_to pastes_path
    end
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  def new
    redirect_to new_user_session_path, flash: { danger: 'Registration is disabled.' }
  end

  def create
    redirect_to new_user_session_path, flash: { danger: 'Registration is disabled.' }
  end

  private

  def sign_up_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:api_key, :email, :password, :password_confirmation, :current_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-danger"> <button type="button"
    class="close" data-dismiss="alert">x</button>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/pastes_helper.rb
module PastesHelper
  def paste_expires_in(paste)
    current_datetime = Proc.new { Time.now }.call

    distance_of_time_in_words(current_datetime, paste.expires_at)
  end
end

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :paste_id, { value: params[:id] } %>

  <div class="form-group">
    <%= f.text_area :body, class: "form-control", style: "margin-top: 20px;" %>
  </div>

  <div class="actions">
    <%= f.submit "Add Comment", class: "btn btn-default" %>
  </div>
<% end %>

app/views/comments/_list.html.erb
<% if comments.blank? %>

<% else %>
  <div class="comments">
    <% comments.each do |comment| %>
      <div class="media">
        <div class="media-left">
          <%= image_tag comment.user.gravatar_url, secure: true %>
        </div>
        <div class="media-body">
          <h4 class="media-heading"><%= "#{comment.user_email} - #{comment.created_at.to_formatted_s(:short)}" %></h4>
          <%= comment.body %>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>arowana</title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <div class="content-wrapper">
      <%= render "shared/navbar" %>
      <% unless flash.empty? %>
        <div class="container-fluid">
          <%= render 'shared/flash_message' %>
        </div>
      <% end %>
      <div class="container-fluid">
        <div class="book">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/pastes/_form.html.erb
<%= form_for(@paste) do |f| %>
  <% if @paste.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@paste.errors.count, "error") %> prohibited this paste from being saved:</h2>

      <ul>
      <% @paste.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, class: "control-label" %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :body, class: "control-label" %>
    <%= f.text_area :body, class: "form-control", rows: "20" %>
  </div>

  <div class="form-group">
    <%= f.label :language, class: "control-label" %>
    <%= f.select :language, Paste.languages.keys.to_a, {  }, { class: "select form-control" } %>
  </div>

  <div class="form-group">
    <%= f.label :expires_at, class: "control-label" %>
    <%= f.datetime_local_field :expires_at, class: "form-control" %>
  </div>

  <div class="actions">
    <%= f.submit "Save", class: "btn btn-default" %>
  </div>
<% end %>

app/views/pastes/_list.html.erb
<h1>Pastes</h1>

<table class="table table-hover pastes-table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Comments</th>
      <th>Submitted By</th>
      <th>Expires</th>
    </tr>
  </thead>
  <tbody>
    <% @pastes.each do |p| %>
      <tr class="paste-link" data-href="<%= paste_path(p) %>">
        <td><%= p.name %></td>
        <td><%= p.comments.count %></td>
        <td><%= p.user.email %></td>
        <td><%= paste_expires_in(p) unless p.expires_at.nil? %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @pastes, :theme => 'twitter-bootstrap-3' %>

app/views/pastes/edit.html.erb
<div class="page-one">
  <%= render "list" %>
</div>

<div class="page-two">
  <h1>Edit</h1>
  <%= render 'form' %>
</div>

app/views/pastes/index.html.erb
<div class="page-one">
  <%= render "list" %>
</div>

<div class="page-two">
  Please select a paste from the left
</div>

app/views/pastes/new.html.erb
<div class="page-one">
  <%= render "list" %>
</div>

<div class="page-two">
  <h1>New</h1>
  <%= render 'form' %>
</div>

app/views/pastes/show.html.erb
<div class="page-one">
  <%= render "list" %>
</div>

<div class="page-two">
  <h1>
    <%= @paste.name %>
    <div class="pull-right">
      <%= link_to "Edit", edit_paste_path(@paste), class: "btn btn-default" %>
    </div>
  </h1>
  <div class="paste-info">
    <span class="submitted-by subtitle">Submitted by: <%= @paste.user_email %></span>
    <span class="language subtitle">Language: <%= @paste.language %></span>
    <span class="expires-at subtitle">Expires: <%= @paste.expires_at.to_formatted_s(:short) unless @paste.expires_at.nil? %></span>
  </div>
  <pre class="paste-body"><%= @paste.body %></pre>
  <h3>Comments</h3>
  <%= render partial: "comments/list", locals: { comments: @paste.comments } %>
  <%= render "comments/form" %>
</div>

app/views/shared/_flash_message.html.erb
<% flash.each do |key, value| %>
  <%= content_tag :div, value, class: "alert alert-#{key}" %>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to root_path, class: "navbar-brand" do %>
        <i class="fa fa-clipboard"></i> arowana
      <% end %>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <% if user_signed_in? %>
        <%= link_to "New Paste", new_paste_path, class: "btn btn-success navbar-btn" %>
      <% end %>
      <ul class="nav navbar-nav">
      </ul>
      <ul class="nav navbar-nav navbar-right" data-no-turbolink>
        <% if user_signed_in? %>
          <li><%= link_to('Profile', edit_user_registration_path) %></li>
          <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
        <% else %>
          <li><%= link_to('Login', new_user_session_path)  %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>